api:
  port: 8080
  poc_callback_url: http://localhost:8080
  public_url: http://localhost:8080
nodes:
  - id: node1
    host: localhost
    inference_port: 2020
    max_concurrent: 1
    models:
      - Qwen/Qwen2.5-7B-Instruct
chain_node:
  url: http://join1-node:26657
  ml_ops_key_name: "alice"
  account_public_key: ""
  keyring_backend: "test"
  keyring_dir: "/root/.inference"
  is_genesis: false
