api:
  port: 8080
  poc_callback_host: localhost
nodes:
  - id: node1
    host: localhost
    inference_port: 2020
    max_concurrent: 1
    models:
      - unsloth/llama-3-8b-Instruct
chain_node:
  url: http://localhost:26657
  account_name: "alice"
  keyring_backend: "test"
  keyring_dir: "~/.inference" # We use a custom function to expand ~ to /root
