// Phase 2: gRPC surface for the testenv mock-chain service.
//
// The proto mirrors the current devshard/bridge.MainnetBridge query and
// action shape so devshard/testenv/bridge.GRPCBridge (Phase 4) can satisfy
// the production bridge interface without any adapter glue.
//
// See devshard/docs/testenv.md §Phase 2 and §3.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: mockchain.proto

package mockchainpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MockChain_GetDevshardEscrow_FullMethodName = "/devshard.testenv.mockchain.v1.MockChain/GetDevshardEscrow"
	MockChain_GetParticipant_FullMethodName    = "/devshard.testenv.mockchain.v1.MockChain/GetParticipant"
	MockChain_GetGrantees_FullMethodName       = "/devshard.testenv.mockchain.v1.MockChain/GetGrantees"
	MockChain_CreateEscrow_FullMethodName      = "/devshard.testenv.mockchain.v1.MockChain/CreateEscrow"
	MockChain_SettleEscrow_FullMethodName      = "/devshard.testenv.mockchain.v1.MockChain/SettleEscrow"
)

// MockChainClient is the client API for MockChain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockChainClient interface {
	// GetDevshardEscrow returns the seeded escrow by id.
	GetDevshardEscrow(ctx context.Context, in *GetDevshardEscrowRequest, opts ...grpc.CallOption) (*GetDevshardEscrowResponse, error)
	// GetParticipant returns the host address → URL mapping.
	GetParticipant(ctx context.Context, in *GetParticipantRequest, opts ...grpc.CallOption) (*GetParticipantResponse, error)
	// GetGrantees enumerates warm-key grantees for (cold) validator_address.
	// The testenv returns every participant address so warm-key checks always pass.
	GetGrantees(ctx context.Context, in *GetGranteesRequest, opts ...grpc.CallOption) (*GetGranteesResponse, error)
	// CreateEscrow (re-)seeds the pre-configured escrow. Idempotent; mainly
	// used by operator tooling that asserts the chain state before starting
	// a run.
	CreateEscrow(ctx context.Context, in *CreateEscrowRequest, opts ...grpc.CallOption) (*CreateEscrowResponse, error)
	// SettleEscrow submits a settlement payload to be verified against the
	// pinned group. The server runs devshard/state.VerifySettlement.
	SettleEscrow(ctx context.Context, in *SettleEscrowRequest, opts ...grpc.CallOption) (*SettleEscrowResponse, error)
}

type mockChainClient struct {
	cc grpc.ClientConnInterface
}

func NewMockChainClient(cc grpc.ClientConnInterface) MockChainClient {
	return &mockChainClient{cc}
}

func (c *mockChainClient) GetDevshardEscrow(ctx context.Context, in *GetDevshardEscrowRequest, opts ...grpc.CallOption) (*GetDevshardEscrowResponse, error) {
	out := new(GetDevshardEscrowResponse)
	err := c.cc.Invoke(ctx, MockChain_GetDevshardEscrow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockChainClient) GetParticipant(ctx context.Context, in *GetParticipantRequest, opts ...grpc.CallOption) (*GetParticipantResponse, error) {
	out := new(GetParticipantResponse)
	err := c.cc.Invoke(ctx, MockChain_GetParticipant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockChainClient) GetGrantees(ctx context.Context, in *GetGranteesRequest, opts ...grpc.CallOption) (*GetGranteesResponse, error) {
	out := new(GetGranteesResponse)
	err := c.cc.Invoke(ctx, MockChain_GetGrantees_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockChainClient) CreateEscrow(ctx context.Context, in *CreateEscrowRequest, opts ...grpc.CallOption) (*CreateEscrowResponse, error) {
	out := new(CreateEscrowResponse)
	err := c.cc.Invoke(ctx, MockChain_CreateEscrow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockChainClient) SettleEscrow(ctx context.Context, in *SettleEscrowRequest, opts ...grpc.CallOption) (*SettleEscrowResponse, error) {
	out := new(SettleEscrowResponse)
	err := c.cc.Invoke(ctx, MockChain_SettleEscrow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockChainServer is the server API for MockChain service.
// All implementations must embed UnimplementedMockChainServer
// for forward compatibility
type MockChainServer interface {
	// GetDevshardEscrow returns the seeded escrow by id.
	GetDevshardEscrow(context.Context, *GetDevshardEscrowRequest) (*GetDevshardEscrowResponse, error)
	// GetParticipant returns the host address → URL mapping.
	GetParticipant(context.Context, *GetParticipantRequest) (*GetParticipantResponse, error)
	// GetGrantees enumerates warm-key grantees for (cold) validator_address.
	// The testenv returns every participant address so warm-key checks always pass.
	GetGrantees(context.Context, *GetGranteesRequest) (*GetGranteesResponse, error)
	// CreateEscrow (re-)seeds the pre-configured escrow. Idempotent; mainly
	// used by operator tooling that asserts the chain state before starting
	// a run.
	CreateEscrow(context.Context, *CreateEscrowRequest) (*CreateEscrowResponse, error)
	// SettleEscrow submits a settlement payload to be verified against the
	// pinned group. The server runs devshard/state.VerifySettlement.
	SettleEscrow(context.Context, *SettleEscrowRequest) (*SettleEscrowResponse, error)
	mustEmbedUnimplementedMockChainServer()
}

// UnimplementedMockChainServer must be embedded to have forward compatible implementations.
type UnimplementedMockChainServer struct {
}

func (UnimplementedMockChainServer) GetDevshardEscrow(context.Context, *GetDevshardEscrowRequest) (*GetDevshardEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevshardEscrow not implemented")
}
func (UnimplementedMockChainServer) GetParticipant(context.Context, *GetParticipantRequest) (*GetParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipant not implemented")
}
func (UnimplementedMockChainServer) GetGrantees(context.Context, *GetGranteesRequest) (*GetGranteesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrantees not implemented")
}
func (UnimplementedMockChainServer) CreateEscrow(context.Context, *CreateEscrowRequest) (*CreateEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEscrow not implemented")
}
func (UnimplementedMockChainServer) SettleEscrow(context.Context, *SettleEscrowRequest) (*SettleEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleEscrow not implemented")
}
func (UnimplementedMockChainServer) mustEmbedUnimplementedMockChainServer() {}

// UnsafeMockChainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockChainServer will
// result in compilation errors.
type UnsafeMockChainServer interface {
	mustEmbedUnimplementedMockChainServer()
}

func RegisterMockChainServer(s grpc.ServiceRegistrar, srv MockChainServer) {
	s.RegisterService(&MockChain_ServiceDesc, srv)
}

func _MockChain_GetDevshardEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevshardEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockChainServer).GetDevshardEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockChain_GetDevshardEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockChainServer).GetDevshardEscrow(ctx, req.(*GetDevshardEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockChain_GetParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockChainServer).GetParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockChain_GetParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockChainServer).GetParticipant(ctx, req.(*GetParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockChain_GetGrantees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGranteesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockChainServer).GetGrantees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockChain_GetGrantees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockChainServer).GetGrantees(ctx, req.(*GetGranteesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockChain_CreateEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockChainServer).CreateEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockChain_CreateEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockChainServer).CreateEscrow(ctx, req.(*CreateEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockChain_SettleEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockChainServer).SettleEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockChain_SettleEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockChainServer).SettleEscrow(ctx, req.(*SettleEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MockChain_ServiceDesc is the grpc.ServiceDesc for MockChain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockChain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devshard.testenv.mockchain.v1.MockChain",
	HandlerType: (*MockChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevshardEscrow",
			Handler:    _MockChain_GetDevshardEscrow_Handler,
		},
		{
			MethodName: "GetParticipant",
			Handler:    _MockChain_GetParticipant_Handler,
		},
		{
			MethodName: "GetGrantees",
			Handler:    _MockChain_GetGrantees_Handler,
		},
		{
			MethodName: "CreateEscrow",
			Handler:    _MockChain_CreateEscrow_Handler,
		},
		{
			MethodName: "SettleEscrow",
			Handler:    _MockChain_SettleEscrow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mockchain.proto",
}
