apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: api
        image: api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: public-api
        - containerPort: 9100
          name: ml-api
        - containerPort: 9200
          name: admin-api
        - containerPort: 9300
          name: ml-grpc-server
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: NODE_CONFIG_PATH
          value: "/root/node_config.json"
        - name: DAPI_API__POC_CALLBACK_URL
          value: "http://api:9100"
        - name: DAPI_API__ML_GRPC_CALLBACK_ADDRESS
          value: "api:9300"
        - name: DAPI_API__PUBLIC_SERVER_PORT
          value: "9000"
        - name: DAPI_API__ML_SERVER_PORT
          value: "9100"
        - name: DAPI_API__ADMIN_SERVER_PORT
          value: "9200"
        - name: DAPI_API__ML_GRPC_SERVER_PORT
          value: "9300"
        - name: DAPI_CHAIN_NODE__SEED_API_URL
          value: "http://34.9.136.116:30000"
        - name: DAPI_CHAIN_NODE__URL
          value: "http://node:26657"
        - name: CREATE_KEY
          value: "true"
        - name: KEYRING_BACKEND
          value: "test"
        - name: KEYRING_PASSWORD
          value: "default"
        - name: TESTS
          value: "true"
        volumeMounts:
        - name: inference-data
          mountPath: /root/.inference
        - name: node-config
          mountPath: /root/node_config.json
          subPath: node_config.json
      volumes:
      - name: inference-data
        hostPath:
          path: /srv/dai/inference
          type: DirectoryOrCreate
      - name: node-config
        configMap:
          name: node-config-cm
