- model_name: Qwen/Qwen2.5-7B-Instruct
  experiment_name: ""
  description: ""
  prompts_file: prompts.csv
  generate_prompts: true
  num_prompts: 10
  prompt_length: 20000
  num_tasks: 5
  num_runners: 1
  max_tokens: 300
  seed: 1
  node_url: "http://36.189.234.237:19252"
  account_address: "gonka"

- model_name: Qwen/Qwen2.5-7B-Instruct
  experiment_name: ""
  description: ""
  prompts_file: prompts.csv
  generate_prompts: true
  num_prompts: 100
  prompt_length: 2000
  num_tasks: 100
  num_runners: 10
  max_tokens: 300
  seed: 1
  node_url: "http://36.189.234.237:19252"
  account_address: "gonka"


- model_name: Qwen/Qwen2.5-7B-Instruct
  experiment_name: ""
  description: ""
  prompts_file: prompts.csv
  generate_prompts: true
  num_prompts: 10
  prompt_length: 45000
  num_tasks: 5
  num_runners: 1
  max_tokens: 1000
  seed: 1
  node_url: "http://36.189.234.237:19252"
  account_address: "gonka"

- model_name: Qwen/Qwen2.5-7B-Instruct
  experiment_name:  ""
  description: ""
  prompts_file: prompts.csv
  generate_prompts: true
  num_prompts: 10
  prompt_length: 45000
  num_tasks: 10
  num_runners: 5
  max_tokens: 1000
  seed: 2
  node_url: "http://36.189.234.237:19252"
  account_address: "gonka"

- model_name: Qwen/Qwen2.5-7B-Instruct
  experiment_name: ""
  description: ""
  prompts_file: prompts.csv
  generate_prompts: true
  num_prompts: 20
  prompt_length: 45000
  num_tasks: 20
  num_runners: 10
  max_tokens: 1000
  seed: 3
  node_url: "http://36.189.234.237:19252"
  account_address: "gonka"

- model_name: Qwen/Qwen2.5-7B-Instruct
  experiment_name: ""
  description: ""
  prompts_file: prompts.csv
  generate_prompts: true
  num_prompts: 40
  prompt_length: 45000
  num_tasks: 40
  num_runners: 5
  max_tokens: 1000
  seed: 2
  node_url: "http://36.189.234.237:19252"
  account_address: "gonka"
