apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: public
    port: 9000
    targetPort: 9000 # Main public API port
  - name: ml-server
    port: 9100
    targetPort: 9100 # ML callback server
  - name: admin
    port: 9200
    targetPort: 9200 # Admin server
  - name: ml-grpc-server
    port: 9300
    targetPort: 9300 # ML gRPC server
