version: "3.7"

services:
  node:
    command: inferenced start
    container_name: node
    image: gcr.io/decentralized-ai/inferenced
    volumes:
      - .inference:/root/.inference
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc
  api:
    container_name: api
    image: gcr.io/decentralized-ai/api-join
    depends_on:
      - node
    environment:
      - API_CONFIG_PATH=/root/.inference/api-config.yaml
    ports:
      - "8080:8080"
    # It shares the volume with the node, because it needs access to the keyring
    volumes:
      - .inference:/root/.inference
