terraform {
  required_version = ">= 1.5.0"

  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

locals {
  deploy_dir   = var.deploy_dir
  repo_branch  = var.repo_branch
  chain_id     = var.chain_id
  public_domain = var.public_domain

  nodes = {
    genesis = {
      mode             = "genesis"
      ssh_host         = var.public_domain
      ssh_port         = var.genesis_ssh_port
      api_port         = var.genesis_api_port
      internal_api_port = var.genesis_internal_api_port
      p2p_port         = var.genesis_p2p_port
      internal_ip      = var.genesis_internal_ip
      key_name         = var.genesis_key_name
      seed_api_url     = "http://${var.public_domain}:${var.genesis_api_port}"
      seed_node_rpc_url = "http://${var.genesis_internal_ip}:26657"
      seed_node_p2p_url = "tcp://${var.public_domain}:${var.genesis_p2p_port}"
      rpc_server_url_1 = "http://${var.genesis_internal_ip}:26657"
      rpc_server_url_2 = "http://${var.genesis_internal_ip}:26657"
    }
    join_1 = {
      mode             = "join"
      ssh_host         = var.public_domain
      ssh_port         = var.join_1_ssh_port
      api_port         = var.join_1_api_port
      internal_api_port = var.join_1_internal_api_port
      p2p_port         = var.join_1_p2p_port
      internal_ip      = var.join_1_internal_ip
      key_name         = "join-1"
      seed_api_url     = "http://${var.public_domain}:${var.genesis_api_port}"
      seed_node_rpc_url = "http://${var.genesis_internal_ip}:26657"
      seed_node_p2p_url = "tcp://${var.public_domain}:${var.genesis_p2p_port}"
      rpc_server_url_1 = "http://${var.genesis_internal_ip}:26657"
      rpc_server_url_2 = "http://${var.genesis_internal_ip}:26657"
    }
    join_2 = {
      mode             = "join"
      ssh_host         = var.public_domain
      ssh_port         = var.join_2_ssh_port
      api_port         = var.join_2_api_port
      internal_api_port = var.join_2_internal_api_port
      p2p_port         = var.join_2_p2p_port
      internal_ip      = var.join_2_internal_ip
      key_name         = "join-2"
      seed_api_url     = "http://${var.public_domain}:${var.genesis_api_port}"
      seed_node_rpc_url = "http://${var.genesis_internal_ip}:26657"
      seed_node_p2p_url = "tcp://${var.public_domain}:${var.genesis_p2p_port}"
      rpc_server_url_1 = "http://${var.genesis_internal_ip}:26657"
      rpc_server_url_2 = "http://${var.genesis_internal_ip}:26657"
    }
  }

  common_env = {
    KEYRING_PASSWORD        = var.keyring_password
    NODE_CONFIG             = "./node-config.json"
    HF_HOME                 = var.hf_home
    DAPI_API__POC_CALLBACK_URL = "http://api:9100"
    DAPI_CHAIN_NODE__URL    = "http://node:26657"
    DAPI_CHAIN_NODE__P2P_URL = "http://node:26656"
    PORT                    = tostring(var.proxy_port)
    INFERENCE_PORT          = tostring(var.inference_port)
    KEYRING_BACKEND         = "file"
    SYNC_WITH_SNAPSHOTS     = "false"
    SNAPSHOT_INTERVAL       = tostring(var.snapshot_interval)
    IS_TEST_NET             = "true"
    ETHEREUM_NETWORK        = var.ethereum_network
    BEACON_STATE_URL        = var.beacon_state_url
    TESTNET_BASE_DIR        = local.deploy_dir
    CHAIN_ID                = local.chain_id
  }

  rendered_env = {
    for name, node in local.nodes :
    name => join("\n", [
      "# Generated by Terraform. Safe to re-run.",
      "export KEY_NAME=\"${node.key_name}\"",
      "export KEYRING_PASSWORD=\"${local.common_env.KEYRING_PASSWORD}\"",
      "export API_PORT=\"${node.internal_api_port}\"",
      "export PUBLIC_URL=\"http://${local.public_domain}:${node.api_port}\"",
      "export P2P_EXTERNAL_ADDRESS=\"tcp://${local.public_domain}:${node.p2p_port}\"",
      "export NODE_CONFIG=\"${local.common_env.NODE_CONFIG}\"",
      "export HF_HOME=\"${local.common_env.HF_HOME}\"",
      "export SEED_API_URL=\"${node.seed_api_url}\"",
      "export SEED_NODE_RPC_URL=\"${node.seed_node_rpc_url}\"",
      "export DAPI_API__POC_CALLBACK_URL=\"${local.common_env.DAPI_API__POC_CALLBACK_URL}\"",
      "export DAPI_CHAIN_NODE__URL=\"${local.common_env.DAPI_CHAIN_NODE__URL}\"",
      "export DAPI_CHAIN_NODE__P2P_URL=\"${local.common_env.DAPI_CHAIN_NODE__P2P_URL}\"",
      "export SEED_NODE_P2P_URL=\"${node.seed_node_p2p_url}\"",
      "export RPC_SERVER_URL_1=\"${node.rpc_server_url_1}\"",
      "export RPC_SERVER_URL_2=\"${node.rpc_server_url_2}\"",
      "export PORT=\"${local.common_env.PORT}\"",
      "export INFERENCE_PORT=\"${local.common_env.INFERENCE_PORT}\"",
      "export KEYRING_BACKEND=\"${local.common_env.KEYRING_BACKEND}\"",
      "export SYNC_WITH_SNAPSHOTS=\"${local.common_env.SYNC_WITH_SNAPSHOTS}\"",
      "export SNAPSHOT_INTERVAL=\"${local.common_env.SNAPSHOT_INTERVAL}\"",
      "export IS_TEST_NET=\"${local.common_env.IS_TEST_NET}\"",
      "export ETHEREUM_NETWORK=\"${local.common_env.ETHEREUM_NETWORK}\"",
      "export BEACON_STATE_URL=\"${local.common_env.BEACON_STATE_URL}\"",
      "export TESTNET_BASE_DIR=\"${local.common_env.TESTNET_BASE_DIR}\"",
      "export CHAIN_ID=\"${local.common_env.CHAIN_ID}\"",
    ])
  }

  rendered_run_script = {
    for name, node in local.nodes :
    name => join("\n", [
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      "cd \"${local.deploy_dir}\"",
      "source \"${local.deploy_dir}/tf-${name}.env\"",
      "python3 launch.py --mode ${node.mode} --branch ${local.repo_branch} --chainid \"$CHAIN_ID\"",
      "",
    ])
  }
}

resource "null_resource" "node_files" {
  for_each = local.nodes

  triggers = {
    launch_py_sha         = filesha256("${path.module}/launch.py")
    prepare_sh_sha        = filesha256("${path.module}/prepare.sh")
    join_1_sh_sha         = filesha256("${path.module}/join-1.sh")
    join_2_sh_sha         = filesha256("${path.module}/join-2.sh")
    genesis_overrides_sha = filesha256("${path.module}/genesis-overrides.json")
    env_sha               = sha256(local.rendered_env[each.key])
    run_sha               = sha256(local.rendered_run_script[each.key])
  }

  connection {
    type        = "ssh"
    user        = var.ssh_user
    host        = each.value.ssh_host
    port        = each.value.ssh_port
    private_key = file(pathexpand(var.ssh_private_key_path))
    timeout     = "2m"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mkdir -p '${local.deploy_dir}'",
      "sudo chown \"$(id -un)\":\"$(id -gn)\" '${local.deploy_dir}'",
    ]
  }

  provisioner "file" {
    source      = "${path.module}/launch.py"
    destination = "${local.deploy_dir}/launch.py"
  }

  provisioner "file" {
    source      = "${path.module}/genesis-overrides.json"
    destination = "${local.deploy_dir}/genesis-overrides.json"
  }

  provisioner "remote-exec" {
    inline = [
      <<-EOT
      cat > '${local.deploy_dir}/tf-${each.key}.env' <<'EOF'
      ${local.rendered_env[each.key]}
      EOF
      chmod 600 '${local.deploy_dir}/tf-${each.key}.env'
      EOT
      ,
      <<-EOT
      cat > '${local.deploy_dir}/tf-${each.key}-run.sh' <<'EOF'
      ${local.rendered_run_script[each.key]}
      EOF
      chmod +x '${local.deploy_dir}/tf-${each.key}-run.sh'
      EOT
    ]
  }
}

resource "null_resource" "genesis" {
  depends_on = [null_resource.node_files["genesis"]]

  triggers = {
    node_files_id = null_resource.node_files["genesis"].id
  }

  connection {
    type        = "ssh"
    user        = var.ssh_user
    host        = local.nodes.genesis.ssh_host
    port        = local.nodes.genesis.ssh_port
    private_key = file(pathexpand(var.ssh_private_key_path))
    timeout     = "2m"
  }

  provisioner "remote-exec" {
    inline = [
      "bash '${local.deploy_dir}/tf-genesis-run.sh'"
    ]
  }
}

resource "null_resource" "wait_for_genesis_api" {
  depends_on = [null_resource.genesis]

  triggers = {
    genesis_id = null_resource.genesis.id
  }

  provisioner "local-exec" {
    command = <<-EOT
      set -euo pipefail
      for i in $(seq 1 60); do
        if curl -fsS "http://${var.public_domain}:${var.genesis_api_port}/v1/identity" >/dev/null; then
          exit 0
        fi
        sleep 5
      done
      echo "Genesis API did not become healthy in time" >&2
      exit 1
    EOT
  }
}

resource "null_resource" "join_nodes" {
  for_each = {
    for name, node in local.nodes : name => node if name != "genesis"
  }

  depends_on = [
    null_resource.node_files,
    null_resource.wait_for_genesis_api,
  ]

  triggers = {
    node_files_id = null_resource.node_files[each.key].id
    wait_id       = null_resource.wait_for_genesis_api.id
  }

  connection {
    type        = "ssh"
    user        = var.ssh_user
    host        = each.value.ssh_host
    port        = each.value.ssh_port
    private_key = file(pathexpand(var.ssh_private_key_path))
    timeout     = "2m"
  }

  provisioner "remote-exec" {
    inline = [
      "bash '${local.deploy_dir}/tf-${each.key}-run.sh'"
    ]
  }
}
