services:
  tmkms:
    platform: linux/amd64
    image: ghcr.io/product-science/tmkms-softsign-with-keygen:0.1.21
    container_name: tmkms
    restart: unless-stopped
    environment:
      - VALIDATOR_LISTEN_ADDRESS=tcp://node:${TMKMS_PORT:-26658}
    volumes:
      - tmkms_data:/root/.tmkms

  node:
    container_name: node
    platform: linux/amd64
    image: ghcr.io/product-science/inferenced:0.1.21
    # FIXME: enable restart
    # restart: always
    command: ["sh", "./init-docker-genesis.sh"]
    environment:
      - GENESIS_RUN_STAGE=${GENESIS_RUN_STAGE:-keygen}
      - KEY_NAME=genesis
      - SNAPSHOT_INTERVAL=1000
      - SNAPSHOT_KEEP_RECENT=5
      - NODE_CONFIG_PATH=/root/node_config.json
      - P2P_EXTERNAL_ADDRESS=tcp://195.242.13.239:26656
      - CONFIG_p2p__allow_duplicate_ip=true
      - CONFIG_p2p__handshake_timeout=30s
      - CONFIG_p2p__dial_timeout=30s
      - INIT_TGBOT=true
      - TGBOT_PRIVATE_KEY_PASS=defaultpassword
      - TMKMS_PORT=${TMKMS_PORT:-26658}
      - KEYRING_HOME=/root/keyring
    volumes:
      # FIXME: replace back
      # - /srv/dai/inference:/root/.inference
      - ./multigen-tests/genesis/keyring:/root/keyring
      - ./multigen-tests/genesis/node:/root/.inference
      - ./genesis-overrides.json:/root/genesis_overrides.json
      - ./init-docker-genesis.sh:/root/init-docker-genesis.sh
    ports:
      - "26656:26656"
      - "26657:26657"
    expose:
      - "${TMKMS_PORT:-26658}"
    depends_on:
      - tmkms

  api:
    platform: linux/amd64
    image: ghcr.io/product-science/api:0.1.21
    restart: always
    depends_on:
      - node
    environment:
      - KEY_NAME=genesis
      - DAPI_API__POC_CALLBACK_URL=http://10.0.0.1:9100
      - DAPI_API__PUBLIC_URL=http://195.242.13.239:8000
      - DAPI_CHAIN_NODE__IS_GENESIS=true
      - DAPI_CHAIN_NODE__URL=http://10.0.0.1:26657
      - DAPI_API__PUBLIC_SERVER_PORT=9000
      - DAPI_API__ML_SERVER_PORT=9100
      - DAPI_API__ADMIN_SERVER_PORT=9200
      - NODE_CONFIG_PATH=/root/node_config.json
    volumes:
      # FIXME: replace back
      # - /srv/dai/inference:/root/.inference
      # - /srv/dai/dapi:/root/.dapi
      - ./multigen-tests/genesis/node:/root/.inference
      - ./multigen-tests/genesis/api:/root/.dapi
      - ./node-config.json:/root/node_config.json
    ports:
      - "9000:9000"
      - "9100:9100"
      - "9200:9200"

  proxy:
    platform: linux/amd64
    container_name: proxy
    image: ghcr.io/product-science/proxy:0.1.21
    ports:
      - "${API_PORT:-8000}:80"
    environment:
      - API_PORT=9000
      - CHAIN_RPC_PORT=26657
      - CHAIN_API_PORT=1317
      - CHAIN_GRPC_PORT=9090
      - DASHBOARD_PORT=5173
    depends_on:
      - node
      - api
      - explorer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  explorer:
    platform: linux/amd64
    container_name: explorer
    image: ghcr.io/product-science/explorer:latest
    expose:
      - "5173"
    restart: unless-stopped

volumes:
  tmkms_data:
