apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-2
  labels:
    app: inference-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-2
  template:
    metadata:
      labels:
        app: inference-2
    spec:
      enableServiceLinks: false # Prevent k8s from propagating vars like {SERVICE_NAME}_PORT inside the container
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-4
      hostIPC: true
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: inference-2
        image: inference
        command:
        - /app/entrypoint.sh
        - uvicorn
        - api.app:app
        - --host=0.0.0.0
        - --port=8080
        ports:
        - containerPort: 8080
          name: poc-api
        - containerPort: 5000
          name: inference-api
        env:
        - name: HF_HOME
          value: "/root/.cache"
        - name: HF_HUB_ENABLE_HF_TRANSFER
          value: "false"
        - name: VLLM_ATTENTION_BACKEND
          value: "FLASHINFER"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: cache
          mountPath: /root/.cache
      volumes:
      - name: cache
        hostPath:
          path: /mnt/shared
          type: DirectoryOrCreate
