apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slot-store
  namespace: binary-singularity
  labels:
    app.kubernetes.io/part-of: gonka
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
