apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    url: http://victoria-metrics:8428
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: "2s"          # matches our scrape_interval
      exemplarTraceIdDestinations: []

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      maxLines: 5000
