services:
  chain-node:
    command: ["sh", "./init-docker-genesis.sh"]
    environment:
      - IS_GENESIS=true
      - INIT_TGBOT=false
      - TGBOT_PRIVATE_KEY_PASS=${TGBOT_PRIVATE_KEY_PASS:-defaultpassword}
      - PUBLIC_URL=${PUBLIC_URL}
    ports:
      - "9090:9090"   # Additional gRPC port for genesis
      - "9091:9091"   # Additional gRPC-web port for genesis
      - "1317:1317"   # REST API port for genesis

  api:
    environment:
      - DAPI_CHAIN_NODE__IS_GENESIS=true
      - TESTS=true