services:
  chain-node:
    container_name: ${KEY_NAME}-node
    image: ghcr.io/product-science/inferenced
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    environment:
      - SEED_NODE_RPC_URL=${SEED_NODE_RPC_URL}
      - SEED_NODE_P2P_URL=${SEED_NODE_P2P_URL}
      - KEY_NAME=${KEY_NAME}
      - RPC_SERVER_URL_2=${RPC_SERVER_URL_2}
      - RPC_SERVER_URL_1=${RPC_SERVER_URL_1}
      - SYNC_WITH_SNAPSHOTS=${SYNC_WITH_SNAPSHOTS}
      - SNAPSHOT_INTERVAL=100
      - SNAPSHOT_KEEP_RECENT=5
      - DEBUG=false
    ports:
      - "${RPC_PORT}:26657"
      - "${P2P_PORT}:26656"
    networks:
      - chain-public

  api:
    container_name: ${KEY_NAME}-api
    image: ghcr.io/product-science/api
    volumes:
        - ./prod-local/${KEY_NAME}:/root/.inference
        - ./${NODE_CONFIG}:/root/node_config.json
    ports:
      - "${PUBLIC_SERVER_PORT}:9000"
      - "${ML_SERVER_PORT}:9100"
      - "${ADMIN_SERVER_PORT}:9200"
      - "${ML_GRPC_SERVER_PORT}:9300"
    environment:
      - KEY_NAME=${KEY_NAME}
      - NODE_HOST=${KEY_NAME}-node
      - DAPI_API__POC_CALLBACK_URL=${POC_CALLBACK_URL}
      - DAPI_API__PUBLIC_URL=${PUBLIC_URL}
      - DAPI_API__PUBLIC_SERVER_PORT=9000
      - DAPI_API__ML_SERVER_PORT=9100
      - DAPI_API__ADMIN_SERVER_PORT=9200
      - DAPI_API__ML_GRPC_SERVER_PORT=9300
      - DAPI_API__TEST_MODE=true
      - DAPI_CHAIN_NODE__SEED_API_URL=${SEED_API_URL}
      - NODE_CONFIG_PATH=/root/node_config.json
      - DEBUG=false
    networks:
      - chain-public

  mock-server:
    container_name: ${KEY_NAME}-mock-server
    image: inference-mock-server
    build:
      context: ../testermint
      dockerfile: Dockerfile
    environment:
      - KEY_NAME=${KEY_NAME}
    ports:
      - "${WIREMOCK_PORT}:8080"
    networks:
      - chain-public

networks:
  chain-public:
    name: chain-public
