services:
  mock-server-2:
    container_name: ${KEY_NAME}-mock-server-2
    image: inference-mock-server
    build:
      context: ../testermint
      dockerfile: Dockerfile
    environment:
      - KEY_NAME=${KEY_NAME}
    ports:
      - "${WIREMOCK_PORT_2}:8080"
    networks:
      - chain-public

networks:
  chain-public:
    name: chain-public
