services:
  proxy:
    container_name: ${KEY_NAME}-proxy
    image: inference-proxy
    build:
      context: ../proxy
      dockerfile: Dockerfile
    ports:
      - "${PROXY_PORT:-80}:80"  # Configurable external port, defaults to 80
    environment:
      # Configure backend service ports via environment variables
      - KEY_NAME=${KEY_NAME}
      - API_PORT=${API_PORT:-9000}
      - CHAIN_RPC_PORT=${CHAIN_RPC_PORT:-26657}
      - CHAIN_API_PORT=${CHAIN_API_PORT:-1317}
      - CHAIN_GRPC_PORT=${CHAIN_GRPC_PORT:-9090}
      # DASHBOARD_PORT is only set when explorer is included (no default value)
      - DASHBOARD_PORT=${DASHBOARD_PORT}
    depends_on:
      - chain-node
      - api
    networks:
      - chain-public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 