services:
  chain-node:
    container_name: ${KEY_NAME}-node
    image: ghcr.io/product-science/inferenced
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    environment:
      - SEED_NODE_RPC_URL=${SEED_NODE_RPC_URL}
      - SEED_NODE_P2P_URL=${SEED_NODE_P2P_URL}
      - KEY_NAME=${KEY_NAME}
      - RPC_SERVER_URL_2=${RPC_SERVER_URL_2}
      - RPC_SERVER_URL_1=${RPC_SERVER_URL_1}
      - SYNC_WITH_SNAPSHOTS=${SYNC_WITH_SNAPSHOTS}
      - SNAPSHOT_INTERVAL=100
      - SNAPSHOT_KEEP_RECENT=5
      - DEBUG=false
    ports:
      - "${RPC_PORT}:26657"
      - "${P2P_PORT}:26656"
    networks:
      - chain-public

  api:
    container_name: ${KEY_NAME}-api
    image: ghcr.io/product-science/api
    volumes:
        - ./prod-local/${KEY_NAME}:/root/.inference
        - ./${NODE_CONFIG}:/root/node_config.json
    ports:
      - "${PUBLIC_SERVER_PORT}:9000"
      - "${ML_SERVER_PORT}:9100"
      - "${ADMIN_SERVER_PORT}:9200"
      - "${ML_GRPC_SERVER_PORT}:9300"
    environment:
      - KEY_NAME=${KEY_NAME}
      - NODE_HOST=${KEY_NAME}-node
      - DAPI_API__POC_CALLBACK_URL=${POC_CALLBACK_URL}
      - DAPI_API__PUBLIC_URL=${PUBLIC_URL}
      - DAPI_API__PUBLIC_SERVER_PORT=9000
      - DAPI_API__ML_SERVER_PORT=9100
      - DAPI_API__ADMIN_SERVER_PORT=9200
      - DAPI_API__ML_GRPC_SERVER_PORT=9300
      - DAPI_API__TEST_MODE=true
      - DAPI_CHAIN_NODE__SEED_API_URL=${SEED_API_URL}
      - NODE_CONFIG_PATH=/root/node_config.json
      - DEBUG=false
    networks:
      - chain-public

  mock-server:
    container_name: ${KEY_NAME}-mock-server
    image: inference-mock-server
    build:
      context: ../testermint
      dockerfile: Dockerfile
    environment:
      - KEY_NAME=${KEY_NAME}
    ports:
      - "${WIREMOCK_PORT}:8080"
    networks:
      - chain-public

  bridge-node:
    container_name: ${KEY_NAME}-bridge
    image:
      ghcr.io/product-science/bridge-ethereum:latest
    ports:
      - "${GETH_HTTP_PORT:-8545}:8545"  # Geth HTTP
      - "${GETH_WS_PORT:-8546}:8546"    # Geth WebSocket
      - "${GETH_AUTH_PORT:-8551}:8551"  # Geth Auth RPC
      - "${PRYSM_RPC_PORT:-4000}:4000"  # Prysm RPC
      - "${PRYSM_GRPC_PORT:-3500}:3500" # Prysm gRPC Gateway
    volumes:
      - ./prod-local/${KEY_NAME}/ethereum/geth:/data/geth
      - ./prod-local/${KEY_NAME}/ethereum/prysm:/data/prysm
      - ./prod-local/${KEY_NAME}/ethereum/jwt:/data/jwt
      - ./prod-local/${KEY_NAME}/ethereum/logs:/var/log
      - ./temp/persistent-db:/persistent-db
    environment:
      - GETH_DATA_DIR=/data/geth
      - PRYSM_DATA_DIR=/data/prysm
      - JWT_SECRET_PATH=/data/jwt/jwt.hex
      - BRIDGE_API_URL=http://${KEY_NAME}-api:9000/v1/bridge/block
      - BRIDGE_CONTRACT=${BRIDGE_CONTRACT:-0x0d4a11d5EEaaC28EC3F61d100daF4d40471f1852}
      - BEACON_STATE_URL=${BEACON_STATE_URL:-https://beaconstate.info}
      - PERSISTENT_DB_DIR=/persistent-db
      - DEBUG=true
      # Copy start.sh content instead of mounting the file
      - START_SCRIPT_PATH=/usr/local/bin/start.sh
    networks:
      - chain-public
    depends_on:
      - api

networks:
  chain-public:
    name: chain-public
