# This docker-compose file is used to LAUNCH a validator node in Stage 5,
# after the final genesis.json has been created and distributed.
# Both regular validators and the coordinator will use this to start their nodes.

services:
  validator:
    image: ghcr.io/product-science/inferenced:latest
    container_name: validator
    restart: always
    # The command is to run the start-node.sh script.
    command: ["sh", "/root/start-node.sh"]
    volumes:
      # Mount the config directory containing the final genesis.json.
      - ./config:/root/.inference/config
      # Mount the tmkms directory containing the validator's private key.
      - ./tmkms:/root/.tmkms
      # Mount the start script.
      - ./start-node.sh:/root/start-node.sh
    # This file contains the P2P peer list.
    env_file:
      - ./config.env
    ports:
      - "26656:26656"
      - "26657:26657"
    expose:
      - "26658" # TMKMS port
    depends_on:
      - tmkms

  tmkms:
    image: ghcr.io/product-science/tmkms-softsign-with-keygen:0.1.21
    container_name: tmkms
    restart: always
    environment:
      # This tells TMKMS where to find the validator node.
      - VALIDATOR_LISTEN_ADDRESS=tcp://validator:26658
    volumes:
      # This must contain the priv_validator_key.json generated in Stage 1.
      - ./tmkms:/root/.tmkms
