// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devshard/transport/v1/gossip.proto

package rpcpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	rpcpb "devshard/transport/rpcpb"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GossipServiceName is the fully-qualified name of the GossipService service.
	GossipServiceName = "devshard.transport.v1.GossipService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GossipServiceNonceProcedure is the fully-qualified name of the GossipService's Nonce RPC.
	GossipServiceNonceProcedure = "/devshard.transport.v1.GossipService/Nonce"
	// GossipServiceTxsProcedure is the fully-qualified name of the GossipService's Txs RPC.
	GossipServiceTxsProcedure = "/devshard.transport.v1.GossipService/Txs"
)

// GossipServiceClient is a client for the devshard.transport.v1.GossipService service.
type GossipServiceClient interface {
	Nonce(context.Context, *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error)
	Txs(context.Context, *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error)
}

// NewGossipServiceClient constructs a client for the devshard.transport.v1.GossipService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGossipServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GossipServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gossipServiceMethods := rpcpb.File_devshard_transport_v1_gossip_proto.Services().ByName("GossipService").Methods()
	return &gossipServiceClient{
		nonce: connect.NewClient[rpcpb.SignedEnvelope, rpcpb.GossipAck](
			httpClient,
			baseURL+GossipServiceNonceProcedure,
			connect.WithSchema(gossipServiceMethods.ByName("Nonce")),
			connect.WithClientOptions(opts...),
		),
		txs: connect.NewClient[rpcpb.SignedEnvelope, rpcpb.GossipAck](
			httpClient,
			baseURL+GossipServiceTxsProcedure,
			connect.WithSchema(gossipServiceMethods.ByName("Txs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gossipServiceClient implements GossipServiceClient.
type gossipServiceClient struct {
	nonce *connect.Client[rpcpb.SignedEnvelope, rpcpb.GossipAck]
	txs   *connect.Client[rpcpb.SignedEnvelope, rpcpb.GossipAck]
}

// Nonce calls devshard.transport.v1.GossipService.Nonce.
func (c *gossipServiceClient) Nonce(ctx context.Context, req *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error) {
	return c.nonce.CallUnary(ctx, req)
}

// Txs calls devshard.transport.v1.GossipService.Txs.
func (c *gossipServiceClient) Txs(ctx context.Context, req *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error) {
	return c.txs.CallUnary(ctx, req)
}

// GossipServiceHandler is an implementation of the devshard.transport.v1.GossipService service.
type GossipServiceHandler interface {
	Nonce(context.Context, *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error)
	Txs(context.Context, *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error)
}

// NewGossipServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGossipServiceHandler(svc GossipServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gossipServiceMethods := rpcpb.File_devshard_transport_v1_gossip_proto.Services().ByName("GossipService").Methods()
	gossipServiceNonceHandler := connect.NewUnaryHandler(
		GossipServiceNonceProcedure,
		svc.Nonce,
		connect.WithSchema(gossipServiceMethods.ByName("Nonce")),
		connect.WithHandlerOptions(opts...),
	)
	gossipServiceTxsHandler := connect.NewUnaryHandler(
		GossipServiceTxsProcedure,
		svc.Txs,
		connect.WithSchema(gossipServiceMethods.ByName("Txs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devshard.transport.v1.GossipService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GossipServiceNonceProcedure:
			gossipServiceNonceHandler.ServeHTTP(w, r)
		case GossipServiceTxsProcedure:
			gossipServiceTxsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGossipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGossipServiceHandler struct{}

func (UnimplementedGossipServiceHandler) Nonce(context.Context, *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devshard.transport.v1.GossipService.Nonce is not implemented"))
}

func (UnimplementedGossipServiceHandler) Txs(context.Context, *connect.Request[rpcpb.SignedEnvelope]) (*connect.Response[rpcpb.GossipAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devshard.transport.v1.GossipService.Txs is not implemented"))
}
