apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gonka.fullname" . }}-scripts
  labels:
    {{- include "gonka.labels" . | nindent 4 }}
data:
  dns-entrypoint.sh: |
    {{- .Files.Get "files/dns-entrypoint.sh" | nindent 4 }}
  oracle.py: |
    {{- .Files.Get "files/oracle.py" | nindent 4 }}
