[package]
name = "my_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-std = "2.2.0"

cw2 = ">=0.16.1"
cw-storage-plus = ">=0.16.1"

serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
thiserror = "1.0"