services:
  mlnode-308:
    # CUDA 12.9 image: ghcr.io/gonka-ai/mlnode:3.0.14-post2-vllm0.25.1-cu129-b300fix
    image: ${MLNODE_IMAGE:-ghcr.io/gonka-ai/mlnode:3.0.14-post2-vllm0.25.1-rc3@sha256:450983bbef31c8e19b8d24edb00c17520af7cc4fb0d186943f3ac3dec4dad387}
    hostname: mlnode-308
    volumes:
      - ${HF_HOME:-${HOME}/.cache}:/root/.cache
    environment:
      - HF_HOME=/root/.cache
      - POC_BATCH_SIZE_DEFAULT=${POC_BATCH_SIZE_DEFAULT:-32}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    command: uvicorn api.app:app --host=0.0.0.0 --port=8080
    restart: always

  inference:
    image: nginx:1.28.0
    hostname: inference
    ports:
      - "${PORT:-8080}:8080"
      - "${INFERENCE_PORT:-5050}:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
