events {}

http {

    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;

    upstream mlnode_v308 {
        zone mlnode_v308 64k;
        server mlnode-308:8080 resolve;
    }

    server {
        listen 8080 ssl;

        ssl_certificate         /etc/nginx/mtls/mlnode.crt;
        ssl_certificate_key     /etc/nginx/mtls/mlnode.key;

        ssl_client_certificate  /etc/nginx/mtls/dapi.crt;
        ssl_verify_client       on;

        ssl_protocols           TLSv1.2 TLSv1.3;

        client_max_body_size      0;
        proxy_connect_timeout     24h;
        proxy_send_timeout        24h;
        proxy_read_timeout        24h;

        location /v3.0.8/ {
            proxy_pass http://mlnode_v308/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass http://mlnode_v308/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    upstream mlnode_v308_port5000 {
        zone mlnode_v308_port5000 64k;
        server mlnode-308:5000 resolve;
    }

    server {
        listen 5000;

        client_max_body_size      0;
        proxy_connect_timeout     24h;
        proxy_send_timeout        24h;
        proxy_read_timeout        24h;

        location /v3.0.8/ {
            proxy_pass http://mlnode_v308_port5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass http://mlnode_v308_port5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
