x-common-config: &common-config
  env_file:
    - ${PROJECT_ROOT}/.env
    - ${PROJECT_ROOT}/packages/pow/.env
  shm_size: "120g"
  volumes:
    - ${CACHE_DIR:-./cache}:/root/.cache

services:
  server:
    <<: *common-config
    build:
      context: ${PROJECT_ROOT}
      dockerfile: packages/pow/Dockerfile
      target: app
    command: uvicorn pow.service.app:app --host 0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["${GPU_DEVICE_ID:-0}"]

  autobs-test:
    <<: *common-config
    build:
      context: ${PROJECT_ROOT}
      dockerfile: packages/pow/Dockerfile
      target: test
    working_dir: /app/packages/pow/tests
    command: python memory_profile_test.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["${GPU_DEVICE_ID:-0}"]

  integration-tests:
    <<: *common-config
    build:
      context: ${PROJECT_ROOT}
      dockerfile: packages/pow/Dockerfile
      target: test
    environment:
      - BATCH_RECIEVER_URL=http://batch-reciever:8080
      - SERVER_URL=http://server:8080
    depends_on:
      - batch-reciever
      - server

  unit-tests:
    <<: *common-config
    build:
      context: ${PROJECT_ROOT}
      dockerfile: packages/pow/Dockerfile
      target: test

  unit-tests-gpu:
    <<: *common-config
    build:
      context: ${PROJECT_ROOT}
      dockerfile: packages/pow/Dockerfile
      target: test
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["${GPU_DEVICE_ID:-0}"]

  batch-reciever:
    <<: *common-config
    build:
      context: ${PROJECT_ROOT}
      dockerfile: packages/pow/Dockerfile
      target: test
    working_dir: /app/packages/pow/tests
    command: python -m uvicorn batch_reciever:app --host 0.0.0.0 --port 8080