name: Multi-Platform Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '^1.22.2' # Replace with your Go version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Makefile build
        run: make build-for-upgrade
