name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'inference-chain/**'
      - 'decentralized-api/**'
      - 'local-test-net/**'
      - 'testermint/**'

jobs:
  integration-tests:
    uses: ./.github/workflows/test-workflow.yml
    with:
      test_name: "Integration Tests"
      test_command: "run-tests"
