name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'inference-chain/**'
      - 'decentralized-api/**'
      - 'local-test-net/**'
      - 'testermint/**'
  issue_comment:
    types: [created]

jobs:
  integration-tests:
    if: ${{
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/run-integration'))}}
    uses: ./.github/workflows/test-workflow.yml
    with:
      test_name: "Integration Tests"
      test_command: "run-tests"