name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      use_matrix:
        description: 'Use matrix strategy for parallel test execution'
        required: false
        type: boolean
        default: true
  push:
    branches:
      - main
    paths:
      - 'inference-chain/**'
      - 'decentralized-api/**'
      - 'local-test-net/**'
      - 'testermint/**'
  issue_comment:
    types: [created]

jobs:
  integration-tests:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/run-integration'))
    uses: ./.github/workflows/test-workflow.yml
    permissions:
      contents: read
      checks: write
    with:
      test_name: "Integration Tests"
      test_command: "run-tests"
      is_pr_comment: ${{ github.event_name == 'issue_comment' }}
      pr_number: ${{ github.event.issue.number || '' }}
      enable_upgrades: true
      use_matrix: ${{ github.event_name == 'workflow_dispatch' && inputs.use_matrix || true }}
