# .github/workflows/build-and-release-to-repo-b.yml (in RepoA)
name: Build and Release to race-releases

on:
  pull_request: # for now
    branches:
      - '**'

  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v2.3.4-alpha, etc.

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '^1.22.2' # Replace with your Go version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Makefile build
        run: make build-for-upgrade
        # This should produce files in:
        # ./public/html/v2/inferenced/*
        # ./public/html/v2/dapi/*

#      - name: Get tag name
#        id: get_tag
#        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Generate GitHub App Installation Token for release
        id: get_release_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: product-science
          repositories: race-releases

      - name: Create Release in race-releases with softprops/action-gh-release
        uses: softprops/action-gh-release@v2 # Or specific commit hash for stability
        with:
          # The token generated by create-github-app-token has permissions for RepoB
          token: ${{ steps.get_release_token.outputs.token }}
          # --- Target Repository ---
          # softprops/action-gh-release uses the GITHUB_REPOSITORY env var by default.
          # To target RepoB, we MUST override it.
          # However, this action ALSO directly supports 'repository' input.
          repository: product-science/race-releases

          # --- Release Details ---
          tag_name: test-release-1 # PRTODO: Use the tag name from the push event
          name: test-release-1
          body: |
            Automated release created from main source tag ${{ github.ref_name }}.
            Build artifacts from the `build-for-upgrade` target.
          draft: false
          prerelease: false # Set to true if these are pre-releases

          # --- Files to Upload ---
          # Provide a multiline string of glob patterns for files to upload
          files: |
            ./public-html/v2/inferenced/*
            ./public-html/v2/dapi/*
