name: Sanity Tests

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-sanity')
    steps:
      - name: Check comment
        run: echo "Comment contains /run-sanity, triggering sanity tests"
    outputs:
      should_run: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-sanity') }}

  sanity-tests:
    needs: check-comment
    if: ${{ github.event_name == 'workflow_dispatch' || needs.check-comment.outputs.should_run == 'true' }}
    uses: ./.github/workflows/test-workflow.yml
    with:
      test_name: "Sanity Tests"
      test_command: "run-sanity"
