name: Sanity Tests

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  sanity-tests:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/run-sanity'))
    uses: ./.github/workflows/test-workflow.yml
    with:
      test_name: "Sanity Tests"
      test_command: "run-sanity"
      is_pr_comment: ${{ github.event_name == 'issue_comment' }}
      pr_number: ${{ github.event.issue.number || '' }}