// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/model.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Model struct {
	ProposedBy             string `protobuf:"bytes,1,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"`
	Id                     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UnitsOfComputePerToken uint64 `protobuf:"varint,3,opt,name=units_of_compute_per_token,json=unitsOfComputePerToken,proto3" json:"units_of_compute_per_token,omitempty"`
	ContextInAiTokens      uint64 `protobuf:"varint,4,opt,name=context_in_ai_tokens,json=contextInAiTokens,proto3" json:"context_in_ai_tokens,omitempty"`
	Quantization           string `protobuf:"bytes,5,opt,name=quantization,proto3" json:"quantization,omitempty"`
	InputPriceInAiTokens   uint64 `protobuf:"varint,6,opt,name=input_price_in_ai_tokens,json=inputPriceInAiTokens,proto3" json:"input_price_in_ai_tokens,omitempty"`
	OutputPriceInAiTokens  uint64 `protobuf:"varint,7,opt,name=output_price_in_ai_tokens,json=outputPriceInAiTokens,proto3" json:"output_price_in_ai_tokens,omitempty"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7b516097210bdb1, []int{0}
}
func (m *Model) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Model.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return m.Size()
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetProposedBy() string {
	if m != nil {
		return m.ProposedBy
	}
	return ""
}

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetUnitsOfComputePerToken() uint64 {
	if m != nil {
		return m.UnitsOfComputePerToken
	}
	return 0
}

func (m *Model) GetContextInAiTokens() uint64 {
	if m != nil {
		return m.ContextInAiTokens
	}
	return 0
}

func (m *Model) GetQuantization() string {
	if m != nil {
		return m.Quantization
	}
	return ""
}

func (m *Model) GetInputPriceInAiTokens() uint64 {
	if m != nil {
		return m.InputPriceInAiTokens
	}
	return 0
}

func (m *Model) GetOutputPriceInAiTokens() uint64 {
	if m != nil {
		return m.OutputPriceInAiTokens
	}
	return 0
}

func init() {
	proto.RegisterType((*Model)(nil), "inference.inference.Model")
}

func init() { proto.RegisterFile("inference/inference/model.proto", fileDescriptor_d7b516097210bdb1) }

var fileDescriptor_d7b516097210bdb1 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0x32, 0x41,
	0x14, 0x85, 0xd9, 0xfd, 0x81, 0x3f, 0x8e, 0xc6, 0xc4, 0x11, 0xcd, 0x6a, 0xb1, 0x10, 0x2a, 0x2a,
	0x28, 0x8c, 0xc6, 0xd8, 0x89, 0x95, 0x85, 0x81, 0x10, 0x2b, 0x9b, 0x09, 0xcc, 0x0e, 0x7a, 0xa3,
	0xcc, 0x1d, 0x67, 0xee, 0x24, 0xe0, 0x53, 0xf8, 0x3e, 0xbe, 0x80, 0x25, 0xa5, 0xa5, 0x81, 0x17,
	0x31, 0xcc, 0x2a, 0x02, 0x89, 0xdd, 0xc9, 0x39, 0xe7, 0x3b, 0xb9, 0xc9, 0x65, 0x55, 0xd0, 0x43,
	0x65, 0x95, 0x96, 0xaa, 0xf5, 0xab, 0x46, 0x98, 0xa9, 0xa7, 0xa6, 0xb1, 0x48, 0xc8, 0xf7, 0x97,
	0x76, 0x73, 0xa9, 0xea, 0x6f, 0x31, 0x2b, 0xdd, 0x2c, 0x4a, 0xbc, 0xca, 0xb6, 0x8d, 0x45, 0x83,
	0x4e, 0x65, 0x62, 0x30, 0x49, 0xa2, 0x5a, 0xd4, 0xd8, 0xea, 0xb1, 0x1f, 0xab, 0x3d, 0xe1, 0xbb,
	0x2c, 0x86, 0x2c, 0x89, 0x83, 0x1f, 0x43, 0xc6, 0x2f, 0xd8, 0xb1, 0xd7, 0x40, 0x4e, 0xe0, 0x50,
	0x48, 0x1c, 0x19, 0x4f, 0x4a, 0x18, 0x65, 0x05, 0xe1, 0xa3, 0xd2, 0xc9, 0xbf, 0x5a, 0xd4, 0x28,
	0xf6, 0x0e, 0x43, 0xa3, 0x33, 0xbc, 0xca, 0xf3, 0xae, 0xb2, 0xb7, 0x8b, 0x94, 0xb7, 0x58, 0x45,
	0xa2, 0x26, 0x35, 0x26, 0x01, 0x5a, 0xf4, 0x21, 0x87, 0x5c, 0x52, 0x0c, 0xd4, 0xde, 0x77, 0x76,
	0xad, 0x2f, 0x21, 0xf4, 0x1d, 0xaf, 0xb3, 0x9d, 0x67, 0xdf, 0xd7, 0x04, 0x2f, 0x7d, 0x02, 0xd4,
	0x49, 0x29, 0x9c, 0xb1, 0xe6, 0xf1, 0x33, 0x96, 0x80, 0x36, 0x9e, 0x84, 0xb1, 0x20, 0xd5, 0xfa,
	0x70, 0x39, 0x0c, 0x57, 0x42, 0xde, 0x5d, 0xc4, 0x2b, 0xdb, 0xe7, 0xec, 0x08, 0x3d, 0xfd, 0x01,
	0xfe, 0x0f, 0xe0, 0x41, 0x5e, 0xd8, 0x20, 0xdb, 0x9d, 0xf7, 0x59, 0x1a, 0x4d, 0x67, 0x69, 0xf4,
	0x39, 0x4b, 0xa3, 0xd7, 0x79, 0x5a, 0x98, 0xce, 0xd3, 0xc2, 0xc7, 0x3c, 0x2d, 0xdc, 0x9d, 0xde,
	0x03, 0x3d, 0xf8, 0x41, 0x53, 0xe2, 0xa8, 0x65, 0x2c, 0x66, 0x5e, 0x92, 0x93, 0xb0, 0xf1, 0x9d,
	0xf1, 0x8a, 0xa6, 0x89, 0x51, 0x6e, 0x50, 0x0e, 0xaf, 0x3a, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0xfb, 0x3d, 0xeb, 0xcd, 0x01, 0x00, 0x00,
}

func (m *Model) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Model) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Model) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OutputPriceInAiTokens != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.OutputPriceInAiTokens))
		i--
		dAtA[i] = 0x38
	}
	if m.InputPriceInAiTokens != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.InputPriceInAiTokens))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Quantization) > 0 {
		i -= len(m.Quantization)
		copy(dAtA[i:], m.Quantization)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Quantization)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ContextInAiTokens != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.ContextInAiTokens))
		i--
		dAtA[i] = 0x20
	}
	if m.UnitsOfComputePerToken != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.UnitsOfComputePerToken))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProposedBy) > 0 {
		i -= len(m.ProposedBy)
		copy(dAtA[i:], m.ProposedBy)
		i = encodeVarintModel(dAtA, i, uint64(len(m.ProposedBy)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintModel(dAtA []byte, offset int, v uint64) int {
	offset -= sovModel(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Model) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProposedBy)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.UnitsOfComputePerToken != 0 {
		n += 1 + sovModel(uint64(m.UnitsOfComputePerToken))
	}
	if m.ContextInAiTokens != 0 {
		n += 1 + sovModel(uint64(m.ContextInAiTokens))
	}
	l = len(m.Quantization)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.InputPriceInAiTokens != 0 {
		n += 1 + sovModel(uint64(m.InputPriceInAiTokens))
	}
	if m.OutputPriceInAiTokens != 0 {
		n += 1 + sovModel(uint64(m.OutputPriceInAiTokens))
	}
	return n
}

func sovModel(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModel(x uint64) (n int) {
	return sovModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Model) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Model: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Model: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnitsOfComputePerToken", wireType)
			}
			m.UnitsOfComputePerToken = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnitsOfComputePerToken |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContextInAiTokens", wireType)
			}
			m.ContextInAiTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContextInAiTokens |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantization", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quantization = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputPriceInAiTokens", wireType)
			}
			m.InputPriceInAiTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InputPriceInAiTokens |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputPriceInAiTokens", wireType)
			}
			m.OutputPriceInAiTokens = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutputPriceInAiTokens |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModel
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModel
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModel
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModel        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModel          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModel = fmt.Errorf("proto: unexpected end of group")
)
